const SHEET_ID = "1ToD2eW-owhGsdE0cswVHNGiX8yHJH87Mdtviz-l6kuM";
const SHEET_NAME = "feedback";
const VALID_RATINGS = ["fire", "solid", "meh"];
function doPost(e) { try { return handleFeedback(JSON.parse(e.postData.contents)); } catch (err) { return jsonResponse({ ok: false, error: err.message }); } }
function doGet(e) { const p = (e && e.parameter) || {}; if (p.to) return handleClick(p); handleFeedback({ edition: p.edition||"", rating: p.rating||"", referrer: p.referrer||"direct" }); return HtmlService.createHtmlOutput('<html><body style="background:#0F172A;color:#22C55E;font-family:monospace;display:flex;justify-content:center;align-items:center;height:100vh;margin:0"><div style="text-align:center"><div style="font-size:32px">✓</div><div style="margin-top:12px">Feedback recebido!</div></div></body></html>'); }
// Camada 2: loga o clique por achado na aba "clicks" e redireciona pra fonte. Nunca bloqueia o redirect.
function handleClick(p) { const to=String(p.to||""); if(!/^https?:\/\//i.test(to))return HtmlService.createHtmlOutput("invalid url"); try{ const ss=SpreadsheetApp.openById(SHEET_ID); const sh=ss.getSheetByName("clicks")||ss.insertSheet("clicks"); sh.appendRow([new Date().toISOString(), parseInt(String(p.ed||"").replace(/[^0-9]/g,""))||"", String(p.id||"").substring(0,20), String(p.aud||"").substring(0,40), String(p.src||"").substring(0,40), String(p.claim||"").substring(0,20), to.substring(0,500)]); }catch(err){} return HtmlService.createHtmlOutput('<!DOCTYPE html><html><body style="background:#0F172A"><script>location.replace('+JSON.stringify(to)+');</script></body></html>'); }
function handleFeedback(data) { const edition=String(data.edition||"").replace(/[^0-9]/g,""),rating=String(data.rating||"").toLowerCase(),referrer=String(data.referrer||"unknown").substring(0,200); if(!edition)return jsonResponse({ok:false,error:"missing edition"}); if(!VALID_RATINGS.includes(rating))return jsonResponse({ok:false,error:"invalid rating"}); const sheet=SpreadsheetApp.openById(SHEET_ID).getSheetByName(SHEET_NAME); if(!sheet)return jsonResponse({ok:false,error:"sheet not found"}); sheet.appendRow([new Date().toISOString(),parseInt(edition),rating,referrer]); return jsonResponse({ok:true,edition,rating}); }
function jsonResponse(data) { return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON); }
